/**
 * Export orchestration — JSON, CSS tokens, full ZIP package.
 */

import type { BrandProfile, BrandAsset, BrandPackage } from '../../types/brand';
import {
  buildBrandPackage,
  validateBrandPackage,
  downloadJson,
  downloadText,
} from './brandPackage';
import { designTokensToCss } from './designTokens';
import { buildZip, textEntry, downloadBlob } from './zipPackage';

export { validateBrandPackage, buildBrandPackage };

export function exportBrandPackageJson(
  brand: BrandProfile,
  assets: BrandAsset[]
): BrandPackage {
  const validation = validateBrandPackage(brand, assets);
  if (!validation.canExport) {
    throw new Error(
      validation.issues
        .filter((i) => i.level === 'error')
        .map((i) => i.message)
        .join(' ')
    );
  }
  const pkg = buildBrandPackage(brand, assets);
  const safeName = brand.brandName.replace(/[^\w\-]+/g, '-').toLowerCase() || 'brand';
  downloadJson(`${safeName}-brand-package-v${pkg.version}.json`, pkg);
  return pkg;
}

export function exportDesignTokensJson(
  brand: BrandProfile,
  assets: BrandAsset[]
): void {
  const validation = validateBrandPackage(brand, assets);
  if (!validation.canExport) {
    throw new Error('Cannot export tokens: brand package validation failed.');
  }
  const pkg = buildBrandPackage(brand, assets);
  const safeName = brand.brandName.replace(/[^\w\-]+/g, '-').toLowerCase() || 'brand';
  downloadJson(`${safeName}-design-tokens.json`, pkg.designTokens);
}

export function exportDesignTokensCss(
  brand: BrandProfile,
  assets: BrandAsset[]
): void {
  const validation = validateBrandPackage(brand, assets);
  if (!validation.canExport) {
    throw new Error('Cannot export CSS: brand package validation failed.');
  }
  const pkg = buildBrandPackage(brand, assets);
  const css = designTokensToCss(pkg.designTokens);
  const safeName = brand.brandName.replace(/[^\w\-]+/g, '-').toLowerCase() || 'brand';
  downloadText(`${safeName}-tokens.css`, css, 'text/css;charset=utf-8');
}

export function exportBrandPackageZip(
  brand: BrandProfile,
  assets: BrandAsset[]
): void {
  const validation = validateBrandPackage(brand, assets);
  if (!validation.canExport) {
    throw new Error(
      validation.issues
        .filter((i) => i.level === 'error')
        .map((i) => i.message)
        .join(' ')
    );
  }
  const pkg = buildBrandPackage(brand, assets);
  const j = (obj: unknown) => JSON.stringify(obj, null, 2);
  const entries = [
    textEntry('brand-package/README.md', buildReadme(pkg)),
    textEntry('brand-package/brand/brand-profile.json', j(pkg.brand)),
    textEntry('brand-package/brand/strategy.json', j(pkg.strategy)),
    textEntry('brand-package/brand/voice.json', j(pkg.voice)),
    textEntry('brand-package/identity/visual-identity.json', j(pkg.visualIdentity || {})),
    textEntry(
      'brand-package/identity/colors.json',
      j(pkg.visualIdentity?.colors || {})
    ),
    textEntry(
      'brand-package/identity/typography.json',
      j(pkg.visualIdentity?.typography || {})
    ),
    textEntry('brand-package/identity/design-tokens.json', j(pkg.designTokens)),
    textEntry(
      'brand-package/identity/design-tokens.css',
      designTokensToCss(pkg.designTokens)
    ),
    textEntry('brand-package/guidelines/foundation.json', j(pkg.guidelines)),
    textEntry('brand-package/assets/index.json', j(pkg.assets.map(summarizeAsset))),
    textEntry('brand-package/assets/roles.json', j(pkg.assetRoles)),
    textEntry('brand-package/package.json', j(pkg.metadata)),
  ];

  // Logos
  const logoConcepts = pkg.visualIdentity?.logo?.concepts || [];
  for (const c of logoConcepts) {
    if (c.svgMarkup) {
      entries.push(
        textEntry(
          `brand-package/logos/${c.role || 'logo'}-${c.id}.svg`,
          c.svgMarkup
        )
      );
    }
  }

  // Assets by category
  for (const a of pkg.assets) {
    const ver =
      a.versions.find((v) => v.id === a.currentVersionId) || a.versions.at(-1);
    if (ver?.svgMarkup) {
      const safe = a.name.replace(/[^\w\-]+/g, '-').toLowerCase();
      entries.push(
        textEntry(
          `brand-package/assets/${a.category}/${safe}-v${ver.version}.svg`,
          ver.svgMarkup
        )
      );
    }
  }

  const blob = buildZip(entries);
  const safeName = brand.brandName.replace(/[^\w\-]+/g, '-').toLowerCase() || 'brand';
  downloadBlob(`${safeName}-brand-package-v${pkg.version}.zip`, blob);
}

function summarizeAsset(a: BrandAsset) {
  return {
    id: a.id,
    name: a.name,
    type: a.type,
    category: a.category,
    approved: a.approved,
    width: a.width,
    height: a.height,
    format: a.format,
    status: a.status,
    currentVersionId: a.currentVersionId,
  };
}

function buildReadme(pkg: BrandPackage): string {
  return `# ${pkg.brand.brandName} — Brand Package

Generated by VEXDYN Brand-in-a-Box
Package version: ${pkg.version}
Exported: ${pkg.metadata.exportedAt}

## Contents

- \`brand/\` — Profile, strategy, voice
- \`identity/\` — Visual identity, colors, typography, design tokens (JSON + CSS)
- \`logos/\` — Logo concept SVGs
- \`assets/\` — Generated assets by category + roles map
- \`guidelines/\` — Foundation copy for brand guidelines

## Design tokens

Use \`identity/design-tokens.json\` or \`identity/design-tokens.css\` in Forge or any frontend.

## Forge

Import this package via the Brand-in-a-Box → Forge handoff, or load the JSON payload produced by the Forge adapter.

Schema version: ${pkg.metadata.schemaVersion}
`;
}
